import React from "react";

export const TopVideosData = [
    {
        title: 'A Brief History Of Creation',
        time: '4:15',
        date: '3 days ago',
        views: '80k',
        author: 'Dollie Blair',
        image: 'A Brief History Of Creation.jpg',
        id: 1,
    },
    {
        title: 'Selecting The Right Hotel',
        time: '8:00',
        date: '1 months ago',
        views: '123k',
        author: 'Dollie Blair',
        image: 'Selecting The Right Hotel.jpg',
        id: 2,
    },
    {
        title: 'Asteroids',
        time: '5:32',
        date: '12 days ago',
        views: '43k',
        author: 'Dollie Blair',
        image: 'Asteroids.jpg',
        id: 3,
    },
    {
        title: 'Telescopes 101',
        time: '6:40',
        date: '6 months ago',
        views: '11k',
        author: 'Dollie Blair',
        image: 'Telescopes 101.jpg',
        id: 4,
    },
    {
        title: 'Medical Care Is Just',
        time: '1:45',
        date: '2 days ago',
        views: '18k',
        author: 'Dollie Blair',
        image: 'Medical Care Is Just.jpg',
        id: 5,
    },
    {
        title: 'Moon Gazing',
        time: '2:12',
        date: '4 months ago',
        views: '67k',
        author: 'Dollie Blair',
        image: 'Moon Gazing.jpg',
        id: 6,
    },
]

export const MidVideos = [
    {
        title: 'Dude You Re Getting A Telescope',
        time: '3:40',
        date: '5 months ago',
        views: '34k',
        author: 'Gussie French',
        image: 'Dude You Re Getting A Telescope.jpg',
        id: 7,
    },
    {
        title: 'Moon Gazing',
        time: '2:12',
        date: '11 months ago',
        views: '54k',
        author: 'Edward Osborne',
        image: 'Moon Gazing 2.jpg',
        id: 8,
    },
    {
        title: 'Moon Gazing',
        time: '2:12',
        date: '4 months ago',
        views: '125k',
        author: 'Dollie Blair',
        image: 'Moon Gazing 3.jpg',
        id: 9,
    },
]

export const BottomVideos = [
    {
        title: 'Astronomy Or Astrology',
        time: '7:36',
        date: '4 months ago',
        views: '240k',
        author: 'Food & Drink',
        image: 'Astronomy Or Astrology.jpg',
        id: 10,
    },
    {
        title: 'Advertising Outdoors',
        time: '2:19',
        date: '15 days ago',
        views: '13k',
        author: 'Food & Drink',
        image: 'Advertising Outdoors.jpg',
        id: 11,
    },
    {
        title: 'Radio Astronomy',
        time: '9:05',
        date: '11 months ago',
        views: '1k',
        author: 'Food & Drink',
        image: 'Radio Astronomy.jpg',
        id: 12,
    },
    {
        title: 'A Good Autoresponder',
        time: '3:40',
        date: '2 month ago',
        views: '45k',
        author: 'Food & Drink',
        image: 'A Good Autoresponder.jpg',
        id: 13,
    },
    {
        title: 'Baby Monitor Technology',
        time: '1:56',
        date: '7 days ago',
        views: '86k',
        author: 'Food & Drink',
        image: 'Baby Monitor Technology.jpg',
        id: 14,
    },
    {
        title: 'Asteroids',
        time: '4:15',
        date: '4 months ago',
        views: '123k',
        author: 'Food & Drink',
        image: 'Asteroids.jpg',
        id: 15,
    },
]

